edit_past_action:
    path:     /edit_past/{id}
    defaults: { _controller: "MainBundle:ActionAdmin:edit_past" }

edit_actual_action:
    path:     /edit_actual/{id}
    defaults: { _controller: "MainBundle:ActionAdmin:edit_actual" }

new_past_action:
    path:     /new_past
    defaults: { _controller: "MainBundle:ActionAdmin:new_past" }

new_actual_action:
    path:     /new_actual
    defaults: { _controller: "MainBundle:ActionAdmin:new_actual" }

delete_past_action:
    path:     /delete_past/{id}
    defaults: { _controller: "MainBundle:ActionAdmin:delete_past" }

delete_actual_action:
    path:     /delete_actual/{id}
    defaults: { _controller: "MainBundle:ActionAdmin:delete_actual" }

show_past_action:
    path:     /show_past
    defaults: { _controller: "MainBundle:ActionAdmin:show_past" }

show_actual_action:
    path:     /show_actual
    defaults: { _controller: "MainBundle:ActionAdmin:show_actual" }