admin_description_index:
    path:     /
    defaults: { _controller: "MainBundle:DescriptionAdmin:index" }
    methods:  GET

admin_description_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:DescriptionAdmin:show" }
    methods:  GET

admin_description_new:
    path:     /new
    defaults: { _controller: "MainBundle:DescriptionAdmin:new" }
    methods:  [GET, POST]

admin_description_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:DescriptionAdmin:edit" }
    methods:  [GET, POST]

admin_description_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:DescriptionAdmin:delete" }
    methods:  DELETE
