admin_media_index:
    path:     /
    defaults: { _controller: "MainBundle:MediaAdmin:index" }
    methods:  GET

admin_media_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:MediaAdmin:show" }
    methods:  GET

admin_media_new:
    path:     /new
    defaults: { _controller: "MainBundle:MediaAdmin:new" }
    methods:  [GET, POST]

admin_media_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:MediaAdmin:edit" }
    methods:  [GET, POST]

admin_media_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:MediaAdmin:delete" }
    methods:  DELETE
