accueil:
    path:     /
    defaults: { _controller: MainBundle:Default:entreprise }

actual:
    path:     /en_cours
    defaults: { _controller: MainBundle:Action:actual }

past:
    path:     /passée
    defaults: { _controller: MainBundle:Action:past }

future:
    path:     /future
    defaults: { _controller: MainBundle:Action:future }

galeries:
    path:     /galeries
    defaults: { _controller: MainBundle:Default:galerie }

origines:
    path:     /origines
    defaults: { _controller: MainBundle:Description:origines }

lieu:
    path:     /lieu
    defaults: { _controller: MainBundle:Description:lieu }

objectif:
    path:     /objectif
    defaults: { _controller: MainBundle:Description:objectif }

equipe:
    path:     /equipe
    defaults: { _controller: MainBundle:Description:equipe }

don:
    path:     /don
    defaults: { _controller: MainBundle:Default:don }

