main_admin_description:
    resource: "@MainBundle/Resources/config/Adminrouting/descriptionAdmin.yml"
    prefix:   /admin/description

main_admin_action:
    resource: "@MainBundle/Resources/config/Adminrouting/actionAdmin.yml"
    prefix:   /admin/action

main_admin_media:
    resource: "@MainBundle/Resources/config/Adminrouting/mediaAdmin.yml"
    prefix:   /admin/media

main_admin_news:
    resource: "@MainBundle/Resources/config/Adminrouting/newsAdmin.yml"
    prefix:   /admin/news

main_admin_carousel:
    resource: "@MainBundle/Resources/config/Adminrouting/carouselAdmin.yml"
    prefix:   /admin/carousel

admin:
    resource: "@MainBundle/Resources/config/Adminrouting/panelAdmin.yml"
    prefix:   /admin

accueil:
    path:     /
    defaults: { _controller: MainBundle:Default:entreprise }

actual:
    path:     /en_cours
    defaults: { _controller: MainBundle:Action:actual }

past:
    path:     /passée
    defaults: { _controller: MainBundle:Action:past }

future:
    path:     /future
    defaults: { _controller: MainBundle:Action:future }

galerie:
    path:     /galerie
    defaults: { _controller: MainBundle:Default:galerie }

news:
    path:     /news
    defaults: { _controller: MainBundle:News:news }

origines:
    path:     /origines
    defaults: { _controller: MainBundle:Description:origines }

lieu:
    path:     /lieu
    defaults: { _controller: MainBundle:Description:lieu }

objectif:
    path:     /objectif
    defaults: { _controller: MainBundle:Description:objectif }

don:
    path:     /don
    defaults: { _controller: MainBundle:Default:don }

dlmedia:
    pattern: /dlmedia
    defaults: { _controller: MainBundle:DlMedia:dlmedia }

contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact }
    requirements:
            _method:  GET|POST

searchMedia:
    pattern: /searchMedia
    defaults: { _controller: MainBundle:Default:searchmedia }

description:
    pattern: /description
    defaults: { _controller: MainBundle:Description:description }

pastActionModal:
    pattern: /passée/{id}
    defaults: { _controller: MainBundle:Action:pastActionModal }


